import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Schedule Classes</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>Hello world!</h1>
      </main>

      <footer>
        <p>All rights reserved.</p>
      </footer>
    </>
  );
};

export default Home;
