import type { NextPage } from 'next';
import Head from 'next/head';
import { useSession, signIn, signOut } from 'next-auth/react';

const Home: NextPage = () => {
  const { data: session, status: loading } = useSession();

  const logout = () => {
    signOut();
    console.log(document.cookie);
  };

  return (
    <>
      <Head>
        <title>Schedule Classes</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>Hello world!</h1>
        {!session && (
          <div>
            Você não está logado. <br />
            Clique no botão abaixo para fazer o login. <br />
            <button onClick={() : Promise<void> => signIn('auth0')}>Fazer login</button>
          </div>
        )}
        {session && (
          <div>
            Logado como {session.user!.email} <br />
            Não é você? Clique no botão abaixo para sair. <br />
            <button onClick={() => logout()}>Sair</button>
          </div>
        )}
        {loading === 'loading' && (
          <div>
            CARREGANDO
          </div>
        )}
      </main>

      <footer>
        <p>All rights reserved.</p>
      </footer>
    </>
  );
};

export default Home;
