import type { NextPage } from 'next';
import Head from 'next/head';
import { useSession } from 'next-auth/react';
import Nav from '../components/nav';
import useSWR from 'swr';
import getaxios from '../utils/getaxios';

const Profile: NextPage = () => {
  const { data: session, status: loading } = useSession();

  const { data, error } = useSWR(`/api/user/${session?.user?.email}`, getaxios);

  return (
    <>
      <Head>
        <title>Profile Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Nav />
        {!session && (
          <div>
            Você não está logado. <br />
            Favor fazer o login para acessar essa página. <br />
          </div>
        )}
        {session && data && (
          <>
          <h2>Bem vindo {data.data.name}</h2>
          <div>
            Logado como {session.user!.email} <br />
            Não é você? Clique no botão sair! <br />
          </div>
          </>

        )}
        {error && (
          <h1>O usuário com o e-mail {session?.user?.email} não existe!</h1>
        )}
        {loading === 'loading' && (
          <div>
            CARREGANDO
          </div>
        )}
      </main>

      <footer>
        <p>All rights reserved.</p>
      </footer>
    </>
  );
};

export default Profile;
