import type { NextPage } from 'next';
import Head from 'next/head';
import { useSession } from 'next-auth/react';
import Nav from '../../components/nav';
import { useCallback, useState } from 'react';
import getaxios from '../../utils/getaxios';
import Link from 'next/link';

interface Teacher {
  _id: string;
  name: string;
  email: string;
  cellphone: string;
  teacher: boolean;
  coins: number;
  courses: string[];
  available_hours: Record<string, number[]>;
  available_locations: string[];
  reviews: Record<string, unknown>[];
  appointments: Record<string, unknown>[];
}

const Search: NextPage = () => {
  const { data: session, status: loading } = useSession();
  const [textInput, setTextInput] = useState('');
  const [data, setData] = useState<Teacher[]>([]);

  const handleSearch = useCallback(() => {
    getaxios(`/api/search/${textInput}`).then((response) => {
      const teachers: Teacher[] = response.data;

      setData(teachers);
    });
  }, [textInput, setData]);

  return (
    <>
      <Head>
        <title>Schedule Classes</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Nav />
        <h2>Bem vindo a página de busca</h2>
        {!session && (
          <div>
            Você não está logado. <br />
            Faça o login para continuar. <br />
          </div>
        )}
        {session && (
          <div>
            Logado como {session.user!.email} <br />
            Não é você? Clique no botão sair. <br />
            <input
            value={textInput}
            onChange={(e) => setTextInput(e.target.value)}
            type="text"
            placeholder="Nome da matéria"
          />
          <button type="submit" onClick={handleSearch}>
            Pesquisar
          </button>
          {data.length !== 0 &&
            data.map((teacher) => (
              <Link href={`/search/${teacher._id}`} key={teacher._id}>
                <a>
                  <h1>{teacher.name}</h1>
                </a>
              </Link>
            ))
          }
          </div>
        )}
        {loading === 'loading' && (
          <div>
            CARREGANDO
          </div>
        )}
      </main>

      <footer>
        <p>All rights reserved.</p>
      </footer>
    </>
  );
};

export default Search;
